### ISSUE TITLE
Correct the translation for "call"

### ISSUE THREAD

**Issue by immany** [AdobeDocs/target-dev.ja-JP#1]
Issue in ./help/dev/implement/client-side/atjs/atjs-functions/adobe-target-getoffers-atjs-2.md

getOffers() に電話してオンデバイス判定を行う

The English description is "Call getOffers() to make an on-device decisioning." Please change the translation to
getOffers() を呼び出し、オンデバイス判定を行う

**Comment by mak-adobe** [comment]
@immany ありがとうございます。G11N-17503のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@immany 修正が完了しました。ご協力ありがとうございました。
